-- Fiche médicament : champs stables supplémentaires
ALTER TABLE "Medicament" ADD COLUMN "forme" TEXT;
ALTER TABLE "Medicament" ADD COLUMN "commentaire" TEXT;

-- Préconisations : un médicament peut en avoir plusieurs (dose/voie/délais
-- selon l'indication). Référentiel à nettoyer et vérifier — n'alimente PAS
-- la suggestion automatique de traitement tant que statut != 'VALIDE'.
CREATE TABLE "Preconisation" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "medicamentId" TEXT NOT NULL,
    "indicationMotif" TEXT,
    "categorieAnimaux" TEXT,
    "agePoidsConcerne" TEXT,
    "dose" REAL,
    "unite" TEXT,
    "doseBase" TEXT,
    "voie" TEXT,
    "frequence" TEXT,
    "dureeValeur" INTEGER,
    "dureeUnite" TEXT,
    "nombreAdministrations" INTEGER,
    "precautions" TEXT,
    "delaiAttenteViandeJ" INTEGER,
    "delaiAttenteLaitTraites" INTEGER,
    "source" TEXT,
    "statut" TEXT NOT NULL DEFAULT 'A_VERIFIER',
    "commentaireVerification" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Preconisation_medicamentId_fkey" FOREIGN KEY ("medicamentId") REFERENCES "Medicament" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- ── Import du référentiel initial fourni par l'utilisateur ──
-- 21 médicaments, 64 lignes brutes -> 51 préconisations après dédup stricte
-- (même libellé + même régime chiffré = doublon ; même libellé + régime
-- différent = conflit conservé et marqué 'A_VERIFIER').
-- INSERT OR IGNORE pour les médicaments : si un nom existe déjà (import CSV
-- historique ou ajout manuel), on ne le duplique/écrase pas ; les nouvelles
-- préconisations sont rattachées par nom à la ligne existante.

INSERT OR IGNORE INTO "Medicament" ("id","nom","categorie","voie","uniteDosage","forme","commentaire","prescriptionRequise","actif","temporaire","createdAt","updatedAt") VALUES ('amphoprim-solution', 'AMPHOPRIM SOLUTION', 'AUTRE', NULL, 'ml', 'Solution injectable', 'Import référentiel initial : catégorie, substance active et forme à confirmer manuellement (non fournies par la source).', false, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO "Medicament" ("id","nom","categorie","voie","uniteDosage","forme","commentaire","prescriptionRequise","actif","temporaire","createdAt","updatedAt") VALUES ('a180', 'A180', 'AUTRE', NULL, 'ml', NULL, 'Import référentiel initial : catégorie, substance active et forme à confirmer manuellement (non fournies par la source).', false, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO "Medicament" ("id","nom","categorie","voie","uniteDosage","forme","commentaire","prescriptionRequise","actif","temporaire","createdAt","updatedAt") VALUES ('butox-7-5-pour-on', 'BUTOX 7.5% POUR ON', 'AUTRE', NULL, 'ml', 'Pour-on', 'Import référentiel initial : catégorie, substance active et forme à confirmer manuellement (non fournies par la source).', false, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO "Medicament" ("id","nom","categorie","voie","uniteDosage","forme","commentaire","prescriptionRequise","actif","temporaire","createdAt","updatedAt") VALUES ('calmagine-solution', 'CALMAGINE SOLUTION', 'AUTRE', NULL, 'ml', 'Solution injectable', 'Import référentiel initial : catégorie, substance active et forme à confirmer manuellement (non fournies par la source).', false, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO "Medicament" ("id","nom","categorie","voie","uniteDosage","forme","commentaire","prescriptionRequise","actif","temporaire","createdAt","updatedAt") VALUES ('carbesia', 'CARBESIA', 'AUTRE', NULL, 'ml', NULL, 'Import référentiel initial : catégorie, substance active et forme à confirmer manuellement (non fournies par la source).', false, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO "Medicament" ("id","nom","categorie","voie","uniteDosage","forme","commentaire","prescriptionRequise","actif","temporaire","createdAt","updatedAt") VALUES ('centraureo-oblet-gyn-cologique', 'CENTRAUREO OBLET GYNÉCOLOGIQUE', 'AUTRE', NULL, 'ml', 'Oblet', 'Import référentiel initial : catégorie, substance active et forme à confirmer manuellement (non fournies par la source).', false, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO "Medicament" ("id","nom","categorie","voie","uniteDosage","forme","commentaire","prescriptionRequise","actif","temporaire","createdAt","updatedAt") VALUES ('dexalone-suspension', 'DEXALONE SUSPENSION', 'AUTRE', NULL, 'ml', 'Suspension injectable', 'Import référentiel initial : catégorie, substance active et forme à confirmer manuellement (non fournies par la source).', false, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO "Medicament" ("id","nom","categorie","voie","uniteDosage","forme","commentaire","prescriptionRequise","actif","temporaire","createdAt","updatedAt") VALUES ('dopram-v-intra-nasale', 'DOPRAM V INTRA NASALE', 'AUTRE', NULL, 'ml', 'Solution intra-nasale', 'Import référentiel initial : catégorie, substance active et forme à confirmer manuellement (non fournies par la source).', false, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO "Medicament" ("id","nom","categorie","voie","uniteDosage","forme","commentaire","prescriptionRequise","actif","temporaire","createdAt","updatedAt") VALUES ('douvistome', 'DOUVISTOME', 'AUTRE', NULL, 'ml', NULL, 'Import référentiel initial : catégorie, substance active et forme à confirmer manuellement (non fournies par la source).', false, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO "Medicament" ("id","nom","categorie","voie","uniteDosage","forme","commentaire","prescriptionRequise","actif","temporaire","createdAt","updatedAt") VALUES ('draxxin', 'DRAXXIN', 'AUTRE', NULL, 'ml', NULL, 'Import référentiel initial : catégorie, substance active et forme à confirmer manuellement (non fournies par la source).', false, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO "Medicament" ("id","nom","categorie","voie","uniteDosage","forme","commentaire","prescriptionRequise","actif","temporaire","createdAt","updatedAt") VALUES ('fascinex', 'FASCINEX', 'AUTRE', NULL, 'ml', NULL, 'Import référentiel initial : catégorie, substance active et forme à confirmer manuellement (non fournies par la source).', false, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO "Medicament" ("id","nom","categorie","voie","uniteDosage","forme","commentaire","prescriptionRequise","actif","temporaire","createdAt","updatedAt") VALUES ('finadyne-transdermal', 'FINADYNE TRANSDERMAL', 'AUTRE', NULL, 'ml', 'Pour-on', 'Import référentiel initial : catégorie, substance active et forme à confirmer manuellement (non fournies par la source).', false, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO "Medicament" ("id","nom","categorie","voie","uniteDosage","forme","commentaire","prescriptionRequise","actif","temporaire","createdAt","updatedAt") VALUES ('imena-l', 'IMENA L', 'AUTRE', NULL, 'ml', NULL, 'Import référentiel initial : catégorie, substance active et forme à confirmer manuellement (non fournies par la source).', false, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO "Medicament" ("id","nom","categorie","voie","uniteDosage","forme","commentaire","prescriptionRequise","actif","temporaire","createdAt","updatedAt") VALUES ('methio-b-12', 'METHIO B 12', 'AUTRE', NULL, 'ml', NULL, 'Import référentiel initial : catégorie, substance active et forme à confirmer manuellement (non fournies par la source).', false, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO "Medicament" ("id","nom","categorie","voie","uniteDosage","forme","commentaire","prescriptionRequise","actif","temporaire","createdAt","updatedAt") VALUES ('oxytetracyclyne-10-vetoquinol', 'OXYTETRACYCLYNE 10% VETOQUINOL', 'AUTRE', NULL, 'ml', NULL, 'Import référentiel initial : catégorie, substance active et forme à confirmer manuellement (non fournies par la source).', false, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO "Medicament" ("id","nom","categorie","voie","uniteDosage","forme","commentaire","prescriptionRequise","actif","temporaire","createdAt","updatedAt") VALUES ('oxytetrin-spray', 'OXYTETRIN SPRAY', 'AUTRE', NULL, 'ml', 'Spray', 'Import référentiel initial : catégorie, substance active et forme à confirmer manuellement (non fournies par la source).', false, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO "Medicament" ("id","nom","categorie","voie","uniteDosage","forme","commentaire","prescriptionRequise","actif","temporaire","createdAt","updatedAt") VALUES ('receptal', 'RECEPTAL', 'AUTRE', NULL, 'ml', NULL, 'Import référentiel initial : catégorie, substance active et forme à confirmer manuellement (non fournies par la source).', false, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO "Medicament" ("id","nom","categorie","voie","uniteDosage","forme","commentaire","prescriptionRequise","actif","temporaire","createdAt","updatedAt") VALUES ('stop-m', 'STOP M', 'AUTRE', NULL, 'ml', NULL, 'Import référentiel initial : catégorie, substance active et forme à confirmer manuellement (non fournies par la source).', false, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO "Medicament" ("id","nom","categorie","voie","uniteDosage","forme","commentaire","prescriptionRequise","actif","temporaire","createdAt","updatedAt") VALUES ('tolfine', 'TOLFINE', 'AUTRE', NULL, 'ml', NULL, 'Import référentiel initial : catégorie, substance active et forme à confirmer manuellement (non fournies par la source).', false, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO "Medicament" ("id","nom","categorie","voie","uniteDosage","forme","commentaire","prescriptionRequise","actif","temporaire","createdAt","updatedAt") VALUES ('valbazen-dix', 'VALBAZEN DIX', 'AUTRE', NULL, 'ml', NULL, 'Import référentiel initial : catégorie, substance active et forme à confirmer manuellement (non fournies par la source).', false, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO "Medicament" ("id","nom","categorie","voie","uniteDosage","forme","commentaire","prescriptionRequise","actif","temporaire","createdAt","updatedAt") VALUES ('vetrimoxin-48h', 'VETRIMOXIN 48H', 'AUTRE', NULL, 'ml', NULL, 'Import référentiel initial : catégorie, substance active et forme à confirmer manuellement (non fournies par la source).', false, true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'amphoprim-solution-p1', "id", 'VEAUX', 10, 'ml', '100KG', 'Intra musculair', '1 fois/Jour', 3, 'JOUR', 3, 5, 5, 'Référentiel fourni (import initial)', 'A_VERIFIER', 'Préconisation "VEAUX" : plusieurs régimes différents relevés dans la source pour ce même libellé — à vérifier.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'AMPHOPRIM SOLUTION';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'amphoprim-solution-p2', "id", 'VEAUX', 10, 'ml', '100KG', 'Intra musculair', '1 fois/Jour', 3, 'JOUR', 3, 5, 4, 'Référentiel fourni (import initial)', 'A_VERIFIER', 'Préconisation "VEAUX" : plusieurs régimes différents relevés dans la source pour ce même libellé — à vérifier.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'AMPHOPRIM SOLUTION';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'a180-p1', "id", 'IV', 3.3, 'ml', '100KG', 'IV', '1 fois/48 H', 1, '48H', NULL, 8, 8, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'A180';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'a180-p2', "id", 'SC', 3.3, 'ml', '100KG', 'SC', '1 fois/48 H', 1, '48H', NULL, 8, 8, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'A180';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'butox-7-5-pour-on-p1', "id", 'POUX', 10, 'ml', 'ANIMAL', 'Appl° Externe', '1 fois/Jour', 1, 'JOUR', 1, 18, 0, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'BUTOX 7.5% POUR ON';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'butox-7-5-pour-on-p2', "id", 'MOUCHE PV INF. 100KG', 10, 'ml', 'ANIMAL', 'PO (pour-on)', '1 fois/Jour', 1, 'JOUR', 1, 18, 0, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'BUTOX 7.5% POUR ON';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'butox-7-5-pour-on-p3', "id", 'MOUCHE 100 KG<PV<300 KG', 20, 'ml', 'ANIMAL', 'PO (pour-on)', '1 fois/Jour', 1, 'JOUR', 1, 18, 0, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'BUTOX 7.5% POUR ON';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'butox-7-5-pour-on-p4', "id", 'MOUCHE PV SUP. 300 KG', 30, 'ml', 'ANIMAL', 'PO (pour-on)', '1 fois/Jour', 1, 'JOUR', 1, 18, 0, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'BUTOX 7.5% POUR ON';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'butox-7-5-pour-on-p5', "id", 'POUX ET GALE', 10, 'ml', 'ANIMAL', 'PO (pour-on)', '1 fois/Jour', 1, 'JOUR', 1, 18, 0, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'BUTOX 7.5% POUR ON';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'butox-7-5-pour-on-p6', "id", 'TIQUES', 15, 'ml', '100KG', 'PO (pour-on)', '1 fois/Jour', 1, 'JOUR', 1, 18, 5, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'BUTOX 7.5% POUR ON';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'calmagine-solution-p1', "id", NULL, 5, 'ml', '100KG', 'Intra musculair', '1 fois/Jour', 1, 'JOUR', 1, 28, 0, 'Référentiel fourni (import initial)', 'A_VERIFIER', 'Préconisation "(sans libellé)" : plusieurs régimes différents relevés dans la source pour ce même libellé — à vérifier.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'CALMAGINE SOLUTION';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'calmagine-solution-p2', "id", NULL, 5, 'ml', '100KG', 'Intra musculair', '1 fois/Jour', 1, 'JOUR', 1, 18, 0, 'Référentiel fourni (import initial)', 'A_VERIFIER', 'Préconisation "(sans libellé)" : plusieurs régimes différents relevés dans la source pour ce même libellé — à vérifier.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'CALMAGINE SOLUTION';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'carbesia-p1', "id", 'PREVENTION PIROPLASMOSE', 2.5, 'ml', '100KG', 'Intra musculair', '1 fois/Jour', 1, 'JOUR', 1, 213, 12, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'CARBESIA';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'carbesia-p2', "id", 'TRAITEMENT ANAPLASMOSE', 2.5, 'ml', '100KG', 'Intra musculair', '1 fois/Jour', 1, 'JOUR', 1, 213, 12, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'CARBESIA';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'carbesia-p3', "id", 'TRAITEMENT PIROPLASMOSE', 1, 'ml', '100KG', 'Intra musculair', '1 fois/Jour', 1, 'JOUR', 1, 213, 12, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'CARBESIA';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'centraureo-oblet-gyn-cologique-p1', "id", 'Intra vaginale', 5, 'oblet', 'ANIMAL', 'IU', '1 fois/Jour', 1, 'JOUR', 1, 7, 0, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'CENTRAUREO OBLET GYNÉCOLOGIQUE';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'centraureo-oblet-gyn-cologique-p2', "id", NULL, 2, 'oblet', 'ANIMAL', 'IU', '1 fois/Jour', 1, 'JOUR', 1, 7, 0, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'CENTRAUREO OBLET GYNÉCOLOGIQUE';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'dexalone-suspension-p1', "id", NULL, 11, 'ml', 'ANIMAL', 'Intra musculair', '1 fois/Jour', 1, 'JOUR', 1, 28, 14, 'Référentiel fourni (import initial)', 'A_VERIFIER', 'Préconisation "(sans libellé)" : plusieurs régimes différents relevés dans la source pour ce même libellé — à vérifier.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'DEXALONE SUSPENSION';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'dexalone-suspension-p2', "id", NULL, 1, 'ml', '100KG', 'Intra musculair', '1 fois/Jour', 1, 'JOUR', 1, 28, 14, 'Référentiel fourni (import initial)', 'A_VERIFIER', 'Préconisation "(sans libellé)" : plusieurs régimes différents relevés dans la source pour ce même libellé — à vérifier.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'DEXALONE SUSPENSION';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'dopram-v-intra-nasale-p1', "id", NULL, 2.5, 'ml', 'ANIMAL', 'Nasal', '1 fois/Jour', 1, 'JOUR', 1, 0, 0, 'Référentiel fourni (import initial)', 'A_VERIFIER', 'Préconisation "(sans libellé)" : plusieurs régimes différents relevés dans la source pour ce même libellé — à vérifier.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'DOPRAM V INTRA NASALE';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'dopram-v-intra-nasale-p2', "id", NULL, 2, 'ml', 'ANIMAL', 'VO', '1 fois/Jour', 1, 'JOUR', 1, 0, 0, 'Référentiel fourni (import initial)', 'A_VERIFIER', 'Préconisation "(sans libellé)" : plusieurs régimes différents relevés dans la source pour ce même libellé — à vérifier.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'DOPRAM V INTRA NASALE';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'douvistome-p1', "id", 'BOVIN + DE 350 KG', 100, 'ml', 'ANIMAL', 'VO', '1 fois/Jour', 1, 'JOUR', 1, 14, 9, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'DOUVISTOME';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'douvistome-p2', "id", 'BOVIN - DE 350 KG', 30, 'ml', '100KG', 'VO', '1 fois/Jour', 1, 'JOUR', 1, 14, 9, 'Référentiel fourni (import initial)', 'A_VERIFIER', 'Préconisation "BOVIN - DE 350 KG" : plusieurs régimes différents relevés dans la source pour ce même libellé — à vérifier.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'DOUVISTOME';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'douvistome-p3', "id", 'BOVIN - DE 350 KG', 30, 'ml', 'ANIMAL', 'VO', '1 fois/Jour', 1, 'JOUR', 1, 14, 9, 'Référentiel fourni (import initial)', 'A_VERIFIER', 'Préconisation "BOVIN - DE 350 KG" : plusieurs régimes différents relevés dans la source pour ce même libellé — à vérifier.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'DOUVISTOME';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'draxxin-p1', "id", 'PAS SUR LAITIERE', 2, 'ml', '100KG', 'SC', '1 fois/Jour', 1, 'JOUR', 1, 22, 0, 'Référentiel fourni (import initial)', 'A_VERIFIER', 'Préconisation "PAS SUR LAITIERE" : plusieurs régimes différents relevés dans la source pour ce même libellé — à vérifier.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'DRAXXIN';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'draxxin-p2', "id", 'PAS SUR LAITIERE', 2, 'ml', '100KG', 'SC', '1 fois/Jour', 1, 'JOUR', 1, 49, 0, 'Référentiel fourni (import initial)', 'A_VERIFIER', 'Préconisation "PAS SUR LAITIERE" : plusieurs régimes différents relevés dans la source pour ce même libellé — à vérifier.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'DRAXXIN';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'fascinex-p1', "id", 'PAS SUR LAITIERE EN LACTATION', 5, 'ml', '100KG', 'VO', '1 fois/Jour', 1, 'JOUR', 1, 56, 30, 'Référentiel fourni (import initial)', 'A_VERIFIER', 'Préconisation "PAS SUR LAITIERE EN LACTATION" : plusieurs régimes différents relevés dans la source pour ce même libellé — à vérifier.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'FASCINEX';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'fascinex-p2', "id", 'PAS SUR LAITIERE EN LACTATION', 12, 'ml', '100KG', 'VO', '1 fois/Jour', 1, 'JOUR', 1, 14, 30, 'Référentiel fourni (import initial)', 'A_VERIFIER', 'Préconisation "PAS SUR LAITIERE EN LACTATION" : plusieurs régimes différents relevés dans la source pour ce même libellé — à vérifier.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'FASCINEX';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'finadyne-transdermal-p1', "id", NULL, 6, 'ml', '100KG', 'PO (pour-on)', '1 fois/Jour', 1, 'JOUR', 1, 12, 3, 'Référentiel fourni (import initial)', 'A_VERIFIER', 'Préconisation "(sans libellé)" : plusieurs régimes différents relevés dans la source pour ce même libellé — à vérifier.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'FINADYNE TRANSDERMAL';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'finadyne-transdermal-p2', "id", NULL, 6, 'ml', '100KG', 'PO (pour-on)', '1 fois/Jour', 1, 'JOUR', 1, 7, 3, 'Référentiel fourni (import initial)', 'A_VERIFIER', 'Préconisation "(sans libellé)" : plusieurs régimes différents relevés dans la source pour ce même libellé — à vérifier.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'FINADYNE TRANSDERMAL';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'imena-l-p1', "id", 'AU DESSUS DE 300KG', 150, 'ml', 'ANIMAL', 'VO', '1 fois/Jour', 1, 'JOUR', 1, 20, 0, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'IMENA L';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'imena-l-p2', "id", 'A PARTIR DE 50 KG', 25, 'ml', 'ANIMAL', 'VO', '1 fois/Jour', 1, 'JOUR', 1, 20, 0, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'IMENA L';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'imena-l-p3', "id", 'JUSQU A 50 KG', 0.5, 'ml', 'KG', 'VO', '1 fois/Jour', 1, 'JOUR', 1, 20, 0, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'IMENA L';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'methio-b-12-p1', "id", 'ADULTE', 25, 'ml', 'ANIMAL', 'IV', '1 fois/Jour', 1, 'JOUR', 1, 0, 0, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'METHIO B 12';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'methio-b-12-p2', "id", 'ADULTE IV', 25, 'ml', 'ANIMAL', 'IV', '1 fois/Jour', 1, 'JOUR', 1, 0, 0, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'METHIO B 12';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'methio-b-12-p3', "id", 'VEAUX', 10, 'ml', 'KG', 'Intra musculair', '1 fois/Jour', 1, 'JOUR', 1, 0, 0, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'METHIO B 12';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'oxytetracyclyne-10-vetoquinol-p1', "id", '3 jours', 50, 'ml', 'ANIMAL', 'IV', '3 fois/Jour', 3, 'JOUR', 9, 14, 6, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'OXYTETRACYCLYNE 10% VETOQUINOL';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'oxytetracyclyne-10-vetoquinol-p2', "id", 'SI DUREE 5 JOURS', 5, 'ml', '100KG', 'Intra musculair', '1 fois/Jour', 5, 'JOUR', 5, 14, 6, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'OXYTETRACYCLYNE 10% VETOQUINOL';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'oxytetrin-spray-p1', "id", NULL, 1, 'ml', 'ANIMAL', 'PO (pour-on)', '1 fois/Jour', 1, 'JOUR', 1, 0, 0, 'Référentiel fourni (import initial)', 'A_VERIFIER', 'Préconisation "(sans libellé)" : plusieurs régimes différents relevés dans la source pour ce même libellé — à vérifier.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'OXYTETRIN SPRAY';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'oxytetrin-spray-p2', "id", NULL, 1, 'Dose', 'ANIMAL', 'PO (pour-on)', '1 fois/Jour', 1, 'JOUR', 1, 0, 0, 'Référentiel fourni (import initial)', 'A_VERIFIER', 'Préconisation "(sans libellé)" : plusieurs régimes différents relevés dans la source pour ce même libellé — à vérifier.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'OXYTETRIN SPRAY';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'receptal-p1', "id", 'ANOESTRUS VRAI', 5, 'ml', 'ANIMAL', 'Intra musculair', '1 fois/Jour', 1, 'JOUR', 1, 0, 0, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'RECEPTAL';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'receptal-p2', "id", 'FECONDATIONS DIFFICILES', 2.5, 'ml', 'ANIMAL', 'Intra musculair', '1 fois/Jour', 1, 'JOUR', 1, 0, 0, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'RECEPTAL';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'receptal-p3', "id", 'KYSTES FOLLICULINIQUES', 5, 'ml', 'ANIMAL', 'Intra musculair', '1 fois/Jour', 1, 'JOUR', 1, 0, 0, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'RECEPTAL';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'stop-m-p1', "id", 'DEUXIEME ET TROISIEME JOURS', 15, 'ml', 'ANIMAL', 'Intra musculair', '1 fois/Jour', 2, 'JOUR', 2, 14, 4, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'STOP M';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'stop-m-p2', "id", 'PREMIER JOUR', 30, 'ml', 'ANIMAL', 'Intra musculair', '1 fois/Jour', 1, 'JOUR', 1, 14, 4, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'STOP M';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'tolfine-p1', "id", 'INTRAMUSCULAIRE', 5, 'ml', '100KG', 'Intra musculair', '48 fois/Jour', 5, 'JOUR', 240, 12, 0, 'Référentiel fourni (import initial)', 'IMPORTE', 'Fréquence "48 fois/JOUR" invraisemblable telle quelle — probable erreur de saisie dans la source, à vérifier.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'TOLFINE';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'tolfine-p2', "id", 'INTRAVEINEUSE', 5, 'ml', '100KG', 'IV', '1 fois/Jour', 1, 'JOUR', 1, 12, 0, 'Référentiel fourni (import initial)', 'IMPORTE', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'TOLFINE';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'valbazen-dix-p1', "id", 'PAS EN LACTATION', 7.5, 'ml', '100KG', 'VO', '1 fois/Jour', 1, 'JOUR', 1, 7, 0, 'Référentiel fourni (import initial)', 'A_VERIFIER', 'Préconisation "PAS EN LACTATION" : plusieurs régimes différents relevés dans la source pour ce même libellé — à vérifier.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'VALBAZEN DIX';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'valbazen-dix-p2', "id", 'PAS EN LACTATION', 7.5, 'ml', '100KG', 'VO', '1 fois/Jour', 1, 'JOUR', 1, 10, 0, 'Référentiel fourni (import initial)', 'A_VERIFIER', 'Préconisation "PAS EN LACTATION" : plusieurs régimes différents relevés dans la source pour ce même libellé — à vérifier.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'VALBAZEN DIX';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'vetrimoxin-48h-p1', "id", NULL, 10, 'ml', '100KG', 'Intra musculair', '1 fois/48 H', 2, '48H', NULL, 18, 3, 'Référentiel fourni (import initial)', 'A_VERIFIER', 'Préconisation "(sans libellé)" : plusieurs régimes différents relevés dans la source pour ce même libellé — à vérifier.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'VETRIMOXIN 48H';
INSERT INTO "Preconisation" ("id","medicamentId","indicationMotif","dose","unite","doseBase","voie","frequence","dureeValeur","dureeUnite","nombreAdministrations","delaiAttenteViandeJ","delaiAttenteLaitTraites","source","statut","commentaireVerification","createdAt","updatedAt") SELECT 'vetrimoxin-48h-p2', "id", NULL, 10, 'ml', '100KG', 'Intra musculair', '1 fois/48 H', 2, '48H', NULL, 14, 4, 'Référentiel fourni (import initial)', 'A_VERIFIER', 'Préconisation "(sans libellé)" : plusieurs régimes différents relevés dans la source pour ce même libellé — à vérifier.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM "Medicament" WHERE "nom" = 'VETRIMOXIN 48H';
